global:
  scrape_interval:     10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'auth-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['auth-service:8085']
        labels:
          application: 'Authentification Service Application'
  - job_name: 'match-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['match-service:8082']
        labels:
          application: 'Match Service Application'
  - job_name: 'messaging-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['messaging-service:8083']
        labels:
          application: 'Messaging Service Application'
  - job_name: 'posts-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['posts-service:8081']
        labels:
          application: 'Notification Service Application'