apiVersion: apps/v1
kind: Deployment
metadata:
  name: match-service
  labels:
    app: match-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: match-service
  template:
    metadata:
      labels:
        app: match-service
    spec:
      containers:
      - name: match-service
        image: myassineboum/sporterz-web:match-service
        ports:
        - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: match-service
spec:
  type: ClusterIP
  selector:
    app: match-service
  ports:
  - protocol: TCP
    port: 8082
    targetPort: 8082

